Repository setup
UltraStar-Deluxe/format pull request #5
Opened 2023-08-30 07:24 UTC by Baklap4

### What does this PR do?

* Sets up the repository as described in #4 
    * EditorConfig added so we maintain the same formatting in every file.
    * Added links to involved parties
    * Added some Github templates

### Closes Issue(s)

Closes #4 

### Motivation

A repository about standardization and formalization should in itself also be structured as otherwise it might defeat the purpose already by not giving a good example.

### More

- [x] Added/updated documentation

### Additional Notes

Please check if all the links are working

2023-08-30 20:35 UTC, bohning approved these changes

2023-08-31 07:47 UTC, Baklap4 commented on README.md
> +### Karaoke software
Missing UltraStar Play

2023-09-01 01:35 UTC, basisbit requested changes
Please add UltraStar Play / Melody Mania to the list.

2023-09-03 14:13 UTC, Baklap4 commented on README.md
> +### Karaoke software
Added

2023-09-03 14:14 UTC, Baklap4 commented
> Please add UltraStar Play / Melody Mania to the list.

@basisbit Updated the branch to include UltrStar Play and Melody Mania

2023-09-03 23:32 UTC, basisbit approved these changes

2023-09-04 09:02 UTC, Baklap4 commented on README.md
> +### Other Software
Updated to make it say "Management software" instead of "Other Software"

And moved UltraSinger to Creator software section. Thanks!

2023-09-04 09:33 UTC, rakuri255 approved these changes

2023-09-04 22:50 UTC, rakuri255 approved these changes

2023-09-08 06:33 UTC, merged