Small corrections: Website
UltraStar-Deluxe/format pull request #60
Opened 2024-07-24 09:50 UTC by marwin89

### What does this PR do?
- Add P1 and P2-Delimiter description to the website (we all forgot them)
- Correct Value in VIDEOGAP-Example: "-1.5"
- Add #PREVIEW to deprecated Tags (#PREVIEWSTART is the official tag)

### Closes Issue(s)
-

### Motivation
- Improve quality of Website

2024-07-24 10:46 UTC, bohning approved these changes

2024-08-26 09:57 UTC, Baklap4 requested changes

2024-08-26 09:57 UTC, Baklap4 commented on docs/index.html
> +                    </div>
P1 & P2 have already been added in https://github.com/UltraStar-Deluxe/format/pull/62,  please remove

2025-01-08 15:26 UTC, marwin89 commented on docs/index.html
> +                    </div>
Removed

2025-01-22 16:14 UTC, Baklap4 commented
Not quite sure about these changes anymore @marwin89 the PR specifies the P1 and P2 delimiter have been removed; yet within the changes i see the same as already on the website? And i don't see the VIDEOGAP anymore

2025-02-01 17:06 UTC, marwin89 commented
Okay, then we don't need this pr anymore 👍🏻

2025-02-01 17:06 UTC, closed without merging